### ISSUE TITLE
Crash on OSX when picking font color OBS crashes

### ISSUE THREAD

**Issue by javajax** [jp9000/OBS#405]
trying to select a font color on OSX and OBS crashes.
Create a new scene.
Add a text.
select font.
Click the font color in the OSX font window.
Select a color -> crash happens.

**Comment by sztanpet** [comment]
wrong project, OBS does not have a mac version,
you are probably looking for obs-studio

**Comment by jp9000** [comment]
We use a bug tracker for obs-studio.  https://obsproject.com/mantis/

Would help us out a bit if you filled it -- also, please include the crash report text (you can link a pastebin with it or attach it as a text file).

Though It might be a known bug that we recently fixed.  We haven't been able to make a release with the fix because our build server is down and the admin went out for holidays.  What a horrible night for a curse.
