### ISSUE TITLE
WebM Support

### ISSUE THREAD

**Issue by steelbrain** [jp9000/OBS#408]
[WebM][1] is a Video Technology by Google which offers higher quality on lower filesize.

It'd be great to have OBS support it.

[1]:http://www.webmproject.org/

**Comment by jp9000** [comment]
You have the wrong project, this is the old deprecated version of OBS, the new version is the multiplatform version here:  https://github.com/jp9000/obs-studio

Being able to support different formats is already planned out, internally it supports direct FFmpeg output, at least if the encoder required for the format you wish to use is efficent enough to be used for live encoding.

It also supports file conversion in the program, though I don't know if the required encoders for webm are currently present in our FFmpeg build (they also might not be free encoders, so that's a factor as well)
